lovelink/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='profiles/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='profiles/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='profiles/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view( template_name='profiles/password_reset_complete.html'),name='password_reset_complete'),
    
    
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    # path('', include('posts.urls')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path
from .views import ( 
    home,
    terms,
    works,
    indexView,
    SorryView,
    MessageSent,
    # ContactView,
    my_profile_view, 
    AvailableProfileListView,
    invites_received_view, 
        
    send_invatation,
    remove_from_friends,
    accept_invatation,
    reject_invatation,
    
    WaitingProfilesListView,
    AcceptedProfilesListView,
    ChangePassword,
    PasswordResetDone,
 
    
    ProfileDetailView,

)
from django.conf.urls import include, url
from . import views
from .views import TableListView, BookingListView, TableDetailView, CancelBookingView

app_name = 'profiles'

urlpatterns = [
    path('terms-conditions/', terms, name='terms-conditions'),
    path('how-it-works/', works, name='how-it-works'),
    path('', indexView.as_view(), name='index-view'),
    path('sorry/', SorryView, name='Sorry-view'),
    path('message-sent/', MessageSent, name='message-sent'),
    path('home/', home.as_view(), name='home-view'),
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
    path('change-password/', ChangePassword.as_view(), name='ChangePasswordView'),
    path('change-password/done/', PasswordResetDone.as_view(), name='PasswordResetDoneView'),
 
    path('my-profile/', my_profile_view, name='my-profile-view'),
    path('available-profiles/', AvailableProfileListView.as_view(), name='all-available-view'),
    path('waiting-profiles/', WaitingProfilesListView.as_view(), name='all-waiting-view'),
    path('accepted-profiles/', AcceptedProfilesListView.as_view(), name='all-accepted-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
    
    path('table-list/', TableListView, name='TableListView'),
    path('booking-list/', BookingListView.as_view(), name='BookingListView'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(), name='CancelBookingView'),
    
    # path('contact/', ContactView, name='contact'),
    # path('contact/', ContactView.as_view(), name='contact'),
    
    
    
    path('table/<category>', TableDetailView.as_view(), name='TableDetailView'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
 
]

profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.conf import settings
from django.urls import reverse_lazy
# Create your models here.
from PIL import Image
from django.conf import settings
import os
from django.utils import timezone





class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(qs)
        print("#########")

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)
        print("#########")

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        print("#########")
        return available
        

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles
    
# def upload_images_path(self, filename):
# 	return f'upload_images/{self.pk}/profile1.PNG'

def default_image():
	return "default_images/profile1.PNG"

def upload_images_path(instance, filename):
    profile_pic_name = 'user_{0}/profile1.PNG'.format(instance.user.id)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_pic_name)

    if os.path.exists(full_path):
    	os.remove(full_path)

    return profile_pic_name


def default_image2():
	return "default_images/profile2.PNG"

def upload_images_path2(instance, filename):
    profile_pic_name2 = 'user_{0}/profile2.PNG'.format(instance.user.id)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_pic_name2)

    if os.path.exists(full_path):
    	os.remove(full_path)

    return profile_pic_name2



def default_image3():
	return "default_images/profile3.PNG"

def upload_images_path3(instance, filename):
    profile_pic_name3 = 'user_{0}/profile3.PNG'.format(instance.user.id)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_pic_name3)

    if os.path.exists(full_path):
    	os.remove(full_path)

    return profile_pic_name3
   

GENDER_CHOICES = (
    ('male', 'male'),
    ('female', 'female'),
)

class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio...", max_length=300)
    email = models.EmailField(max_length=200, blank=False, null= True, unique=True)
    address= models.CharField(max_length=200, blank=False)
    image = models.ImageField(default=default_image, upload_to=upload_images_path)
    image2 =  models.ImageField(default=default_image2, upload_to=upload_images_path2)
    image3 =  models.ImageField(default=default_image3, upload_to=upload_images_path3)
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    nationalid= models.CharField(max_length=16, blank=True)
    telephone= models.CharField(max_length=10,  blank=False, unique=True,null= True)
    age= models.CharField(max_length=2, blank=True)
    gender = models.CharField(max_length=12, default="Your gender", choices=GENDER_CHOICES)
    birth_date = models.DateField(null=True,blank=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    objects = ProfileManager()
    
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"slug": self.slug})
    
    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()
    
   
       
       

    # __initial_first_name = None
    # __initial_last_name = None

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.__initial_first_name = self.first_name
    #     self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        # to_slug = self.slug
        # if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
        if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
        else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

class RelationshipManager(models.Manager):
    def invatations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"
    
 
    
    

class Table(models.Model):
    TABLE_CATEGORIES = (
        ('YAC', 'TABLE 1'),
        ('NAC', 'TABLE 2'),
        ('DEL', 'TABLE 3'),
        ('KIN', 'TABLE 4'),
        ('QUE', 'TABLE 5'),
        ('TAC', 'TABLE 6'),
        ('MAC', 'TABLE 7'),
        ('XEL', 'TABLE 8'),
        ('GIN', 'TABLE 9'),
        ('WUE', 'TABLE 10'), 
        ('YAK', 'TABLE 11'),
        ('NOC', 'TABLE 12'),
        ('DEG', 'TABLE 13'),
        ('KIT', 'TABLE 14'),
        ('QUO', 'TABLE 15'), 
        ('GOC', 'TABLE 16'),
        ('JAC', 'TABLE 17'),
        ('DAL', 'TABLE 18'),
        ('KUN', 'TABLE 19'),
        ('QAE', 'TABLE 20'),
    )
    category = models.CharField(max_length=5, choices=TABLE_CATEGORIES)
    seats = models.IntegerField()
    

    def __str__(self):
        return f'seats={self.seats}. {dict(self.TABLE_CATEGORIES)[self.category]}'    
    
     
class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)   
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()


    def __str__(self):
        return f'From = {self.check_in.strftime("%d-%b-%Y %H:%M")} To = {self.check_out.strftime("%d-%b-%Y %H:%M")}'
    
    def get_table_category(self):
        table_categories=dict(self.table.TABLE_CATEGORIES)
        table_category= table_categories.get(self.table.category)  
        return table_category  
    
    def get_cancel_booking_url(self):  
        return reverse_lazy('profiles:CancelBookingView', args=[self.pk, ])
    
    
    
    
    
class Video(models.Model):
    caption = models.CharField(max_length=300)
    video = models.FileField(upload_to="video/%y")
    
    def __str__(self):
        return self.caption
    
    
class Contact(models.Model):
    subject = models.CharField(max_length=100)
    message = models.TextField()
    author = models.ForeignKey(User,null=True, blank=True, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.subject  

profiles/forms.py
from django import forms
from .models import Profile,Booking, Contact
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm#
from django.contrib.auth import authenticate



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio','gender', 'address', 'age', 'telephone', 'nationalid','image','image2','image3')
 

# class CreateUserForm(UserCreationForm):
#     email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
    
    
# 	class Meta:
# 		model = User
# 		fields = ['username', 'email', 'password1', 'password2']   
  
class CreateUserForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
 
 

	class Meta:
		model = User
		fields = ('email', 'username', 'password1', 'password2', )  
  
  
	def clean_email(self):
			email = self.cleaned_data['email'].lower()
			try:
				user = User.objects.exclude(pk=self.instance.pk).get(email=email)
			except User.DoesNotExist:
				return email
			raise forms.ValidationError('Email "%s" is already exist.' % email)
  
  
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username','email']  
 
 
class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    check_out = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
          
class ContactForm(ModelForm):
	class Meta:
		model = Contact
		fields = '__all__'          
          

profiles/templates/profiles/accepted_profiles.html
{% extends 'profiles/base.html' %}
{% load static %}

{% block title %}
Accpeted 
{% endblock title %}

{% block content %}
 <section class="wrapper">
    <section class="team">
        <div class="container containermain">
            <div class="row  sub_content">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="dividerHeading">
                        <h4><span>In Relation </span></h4>
                    </div>
                </div>
                {% for obj in object_list %}
                {% if request.user in obj.friends.all %}

                <div class="col-lg-3 col-md-3 col-sm-6">
                    <div class="dreamz-team">
                        <div class="pic">
                            
                            <img src="{{obj.image.url}}"alt='no image'style=" height:220px; width:100%;">

                            <div class="social_media_team">
                                <ul class="team_social">
                                    
                                    <li><a class="fb" href="{% url 'profiles:TableListView'%}" data-placement="top" data-toggle="tooltip" title="Book your space"><i class="fas fa-shopping-cart"></i></a></li>

                                    <!-- <form action="{% url 'profiles:reject-invite' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                        <li><button class="cancelbtn" data-placement="top" data-toggle="tooltip" title=" Remove For Friend"><i class="fas fa-times-circle"></i></button></li>
                                        </form> -->

                                        <form action="{% url 'profiles:remove-friend' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                            <li><button class="cancelbtn" data-placement="top" data-toggle="tooltip" title=" End"><i class="fas fa-times-circle"></i></button></li>
                                            </form>    

                               
                                    <li><a class="twtr" href="{{obj.get_absolute_url}}" data-placement="top" data-toggle="tooltip" title="View profile"><i class="fa fa-eye"></i></a></li> 
                
                                </ul>

                            </div>
                        </div>
                        <div class="team_prof">
                            <h3 class="names">{{obj.user}}<small class="coupled">Coupled</small></h3>  
                        </div>
                    </div>
                </div>
                {% endif %}



             {% endfor %}

            </div>
        </div>
    </section>
</section> 


{% endblock content %}

profiles/templates/profiles/navbar.html
{% load static %}
<nav class="navbar fixed-top navbar-light white scrolling-navbar">

    <!-- FOR ALL SCREENS EXCEPT SMALL -->
    <div class="nav-container-1 d-xl-flex d-lg-flex d-md-flex d-sm-none d-none">

      
        <!-- Navbar brand -->
        <a class="navbar-brand text-dark" href="{% url 'profiles:index-view' %}">Remarkable</a>
    
        <ul class="nav nav-items text-dark">

      
    
        <!-- <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'profiles:index-view' %}">How It Works</a>
        </li> -->
    
        <!-- Dropdown -->
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle  text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">Profiles</a>
            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'profiles:home-view' %}">All Profiles</a>
                <a class="dropdown-item" href="{% url 'profiles:all-available-view' %}">Available</a>
                <a class="dropdown-item" href="{% url 'profiles:all-waiting-view' %}">Waiting</a>
                <a class="dropdown-item" href="{% url 'profiles:my-invites-view' %}">my Invite</a>
                <a class="dropdown-item" href="{% url 'profiles:all-accepted-view' %}">My Couple</a>

            </div>
        </li>
        {% endif %}
    
        </ul>
    
    <!-- END NAV SEARCH -->
    
    </div>
    
    
    <!-- Dropdown -->
    {% if user.is_authenticated %}
    <div class="navbar-nav dropdown d-xl-flex d-lg-flex d-md-flex d-sm-none d-none">
        <a class="nav-link text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        <img class="img-circle" src="{{request.user.profile.image.url}}"alt='no image'style=" height:100px; width:100%;">     
        {{ request.user|capfirst }}     
    </a>
        <div class="dropdown-menu dropdown-primary mr-lg-5 mr-md-5" aria-labelledby="navbarDropdownMenuLink">
          
            <a class="dropdown-item" href="{% url 'profiles:my-profile-view' %}">My Profile</a>
            <a class="dropdown-item" href="{% url 'profiles:ChangePasswordView' %}">Password</a>
            {% if user.is_staff%}
            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'profiles:logout' %}">Logout</a>
        </div>
    </div>
    {% else %}
    <div class="navbar-nav dropdown d-xl-flex d-lg-flex d-md-flex d-sm-none d-none">
        <a class="nav-link text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        Get Started
        </a>
        <div class="dropdown-menu dropdown-primary mr-lg-5 mr-md-5" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'profiles:register' %}">Register</a>
            <a class="dropdown-item" href="{% url 'profiles:login' %}">Login</a>
        </div>
    </div>
    {% endif %}
    
    
    <!-- END FOR ALL SCREENS EXCEPT SMALL -->
    
    
    
    <!-- FOR SMALL SCREENS -->
    <div class="nav-container-2 d-flex d-lg-none d-md-none d-sm-flex d-flex">
    
    <div class="d-flex justify-content-start">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
            aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    
     <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="navbarToggleExternalContent">

      
            <!-- Navbar brand -->
        <a class="navbar-brand text-dark" href="{% url 'profiles:index-view' %}">Remarkable</a>
    
        <!-- Links -->
       
  
            <!-- Links -->
        <!-- <ul class="nav nav-items text-dark">
            <li class="nav-item active">
                <a class="nav-link text-dark" href="{% url 'profiles:index-view' %}">How  It Works</a>
            </li>
        </ul> -->

        <ul class="nav nav-items text-dark">
         {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle  text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">Profiles</a>
            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'profiles:home-view' %}">All Profiles</a>
                <a class="dropdown-item" href="{% url 'profiles:all-available-view' %}">Available</a>
                <a class="dropdown-item" href="{% url 'profiles:all-waiting-view' %}">Waiting</a>
                <a class="dropdown-item" href="{% url 'profiles:my-invites-view' %}">my Invite</a>
                <a class="dropdown-item" href="{% url 'profiles:all-accepted-view' %}">My Couple</a>
            </div>
        </li>
        {% endif %}
        </ul>
    
           
        
        <!-- Dropdown -->
        {% if user.is_authenticated %}
        <div class="nav-item dropdown">
            <a class="nav-link text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
        
            <img class="img-circle" src="{{request.user.profile.image.url}}"alt='no image'style=" height:100px; width:100%;"> 
            {{ request.user|capfirst }}     
            </a>
            <div class="dropdown-menu dropdown-primary mr-lg-5 mr-md-5" aria-labelledby="navbarDropdownMenuLink">
              
                <a class="dropdown-item" href="{% url 'profiles:my-profile-view' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'profiles:ChangePasswordView' %}">Password</a>
                {% if user.is_staff%}
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'profiles:logout' %}">Logout</a>
            </div>
        </div>
        {% else %}
        <div class="nav-item dropdown">
            <a class="nav-link text-dark" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            Get Started
            </a>
            <div class="dropdown-menu dropdown-primary mr-lg-5 mr-md-5" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'profiles:register' %}">Register</a>
                <a class="dropdown-item" href="{% url 'profiles:login' %}">Login</a>
            </div>
        </div>

        {% endif %}
        
    
      </div>  <!-- Collapsible content -->
    
    
    </div><!-- END FOR SMALL SCREENS -->
    
    </nav>

profiles/templates/profiles/password_reset_complete.html
{% extends 'profiles/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Reset Complete
{% endblock title %}

{% block content %}
<style type="text/css">
    .card{
        min-height: 100vh;
        height: 100%;
        width: 100%;
    }

    .errorlist{
        color: red;
    }

    @media screen and (max-width: 768px) {
        .card{
          
            width: 95%;
            margin: auto;
        }
      }
      
    </style>

<div class="container">
    <div class="row mt-4">
    <div class="card">
    <!-- <div class="card-header font-weight-bold">
  <center><h5>Reset Password</h5></center>
    </div> -->
    <div class="card-body ml-md-2 p-sm-2 p-0 mt-3">
    <div class="d-flex justify-content-center">
    
        <div class="changepassword-form">  
            <div class="alert alert-info">
                Your password has been set.
            </div>
            <a href="{% url 'profiles:login' %}">Login here</a>
    </div>

    </div>
    </div>
    </div>
    </div>
    </div>
    <br> <br> 

{% endblock content %}

profiles/templates/profiles/table_detail.html
{% extends 'profiles/base.html' %}
{% load static %}

{% block title %}
Booking Detail
{% endblock title %}

{% block content %}

    <div class="container">

        <!--Grid row-->
        <div class="row">
        
        <div class="col-md-7 mt-4">
        <!-- START MAIN Card -->
        <div class="card">
       
        <div class="card-body ml-md-2 p-sm-2 p-0 mt-3">
        
        <!-- border: 1px solid #000; -->
        <div class="d-flex flex-xl-row flex-lg-row flex-md-column flex-sm-column flex-column" style="width: 100%;">
        
       
        
        
        
        <div class="account-attributes d-flex justify-content-start align-items-start vertical-align-center flex-column p-xl-4 p-lg-4 p-md-3 p-sm-3 p-0">
        <div class="d-flex flex-row justify-content-between" style="width: 100%;">
            <div class="d-flex flex-column justify-content-between ml-3">
                <h5 class="text-dark">
                    <strong>
                        Booking Detail
                    </strong>
                </h5>
            </div>
        </div>
        
        <div class="d-flex justify-content-between flex-column mt-3 p-3" style="width: 100%;">
            
                <div class="d-flex justify-content-between flex-row my-1" style="width: 100%;">
                    <div class="text d-flex">
                        <span class='text-dark'>Client:</span>
                    </div>
                    <div class="d-flex">
                        <span class="text text-primary">{{user}}</span>
                    </div>
                </div>
                
                 <div class="d-flex justify-content-between flex-row my-1" style="width: 100%;">
                    <div class="text d-flex">
                        <span class='text-dark'>Table:</span>
                    </div>
                    <div class="d-flex">
                        <span class="text text-primary">{{table_category}}</span>  
                    </div>
                </div>
        
                <form id="booking-form" action="" method="POST">
                    {% csrf_token %}

                    <div class="d-flex justify-content-between flex-row my-1" style="width: 100%;">
                        <div class="text d-flex">
                            <span class='text-dark'>Check In:</span>
                        </div>
                        <div class="d-flex">
                            <input type="datetime-local" id="id_check_in" name="check_in" required> 
                        </div>
                    </div>

                    <div class="d-flex justify-content-between flex-row my-1" style="width: 100%;">
                        <div class="text d-flex">
                            <span class='text-dark'>Check Out:</span>
                        </div>
                        <div class="d-flex">
                            <input type="datetime-local" id="id_check_out" name="check_out" required>
                        </div>
                    </div>
                    <br>
                    
                    <div class="input-div">
                        <a class="btnback" href="{% url 'profiles:TableListView'%}">Back</a>
                        <button class="btnbook" type="submit">Book Hour</button>
                       
                    </div>
                </form>
        
              
        
        </div>
        </div>
        </div>
        <!-- -->
        
        
        
        </div> <!-- END CARD BODY -->
        <br>
        </div> <!-- END MAIN CARD -->
        
        </div>
        <!-- end col -->


        <div class="col-md-5 mb-4 wow fadeIn mt-4">
            <div class="card mb-4">
            <!-- <div class="card-header"><h4>Booking Hour Format</h4></div> -->
            <div class="card-body"> 
                <div class="post-list"> 
                    <table class="centerTable">
                        <thead>
                          <tr>
                            <th>Day</th>
                            <th>Open</th>
                            <th>Close</th>
                             </tr>
                        </thead>
                <tbody>
                <tr>
                  <td data-label="By">Monday to Sunday</td>
                  <td data-label="title">9:00 AM</td>
                  <td data-label="Created"> 8:00 PM</td>
                </tr>
                        </tbody>
                      </table>   



                      <table class="centerTable">
                        <thead>
                          <tr>
                            <th>Booking</th>
                            <th>First Hour</th>
                            <th>Last Hour</th>
                             </tr>
                        </thead>
                <tbody>
                <tr>
                  <td data-label="By">Monday to Sunday</td>
                  <td data-label="title">9:00 AM</td>
                  <td data-label="Created"> 7:00 PM</td>
                </tr>
                        </tbody>
                      </table>      

                </div>

               Notes: You are allowed to Book 1hour of Meeting<br>
               Use this format: Eg 22/11/2020 10:00 (specific hour)<br>
               Do not use this format: Eg 22/11/2020 10:15 (Avoid minutes)
            
         


            </div>
            </div>
            </div>

     </div>       
        
        
        </div> 
        <!-- end row -->
        <br> <br> 

        {% endblock content %}